Fix missing EVP_PKEY_ED25519 build error on libressl
Fixes:
gensio_filter_certauth.c: In function ‘v3_certauth_add_challenge_rsp’:
gensio_filter_certauth.c:838:44: error: ‘EVP_PKEY_ED25519’ undeclared (first use in this function); did you mean ‘EVP_PKEY_DSA1’?
  838 |     if (EVP_PKEY_base_id(sfilter->pkey) == EVP_PKEY_ED25519) {
      |                                            ^~~~~~~~~~~~~~~~
      |                                            EVP_PKEY_DSA1
gensio_filter_certauth.c:838:44: note: each undeclared identifier is reported only once for each function it appears in
gensio_filter_certauth.c: In function ‘certauth_add_challenge_rsp’:
gensio_filter_certauth.c:901:44: error: ‘EVP_PKEY_ED25519’ undeclared (first use in this function); did you mean ‘EVP_PKEY_DSA1’?
  901 |     if (EVP_PKEY_base_id(sfilter->pkey) == EVP_PKEY_ED25519)
      |                                            ^~~~~~~~~~~~~~~~
      |                                            EVP_PKEY_DSA1
gensio_filter_certauth.c: In function ‘certauth_check_challenge’:
gensio_filter_certauth.c:1048:35: error: ‘EVP_PKEY_ED25519’ undeclared (first use in this function); did you mean ‘EVP_PKEY_DSA1’?
 1048 |     if (EVP_PKEY_base_id(pkey) == EVP_PKEY_ED25519)
      |                                   ^~~~~~~~~~~~~~~~
      |                                   EVP_PKEY_DSA1

Signed-off-by: Corey Minyard <cminyard@mvista.com>